name: Firebase Deploy

# This workflow is triggered on pushes to the main branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' # Or whichever version your project requires

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the project if needed (optional step)
    - name: Build project
      run: npm run build

    # Deploy to Firebase Hosting
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v2.2.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: 1//0g4uhAZgCBEbbCgYIARAAGBASNwF-L9IriWIZ9E1ysN0ICQDZSpRrRhQ8JmQRuJGGzzXl8qigmnmPn1j-W8_xfiXuajuQexRCHJU
